"""Centralised prompt templates for the OpenRouter LLM calls."""

KPI_EXTRACTION_PROMPT = (
    "Analysiere den folgenden Textauszug aus einem Geschäftsbericht und extrahiere "
    "ausschließlich eindeutig quantifizierbare, formale und betriebswirtschaftlich "
    "standardisierte finanzielle Kennzahlen (KPIs), die für die Beurteilung der "
    "wirtschaftlichen Substanz von Nachhaltigkeitsaussagen relevant sind. "
    "Wende einen strengen Materialitätsfilter an und extrahiere NUR KPIs aus den "
    "folgenden klar abgegrenzten Kategorien: "

    "1. 'revenue_profit': Umsatz, Erlöse, Revenue, Sales, EBIT, EBITDA, Operating Profit, "
    "Operating Income, Net Income, Jahresüberschuss. "
    "2. 'operational_costs': Operating Costs, Operating Expenses, COGS, "
    "energiebezogene Kosten, F&E-Aufwendungen. "
    "3. 'capex_opex': CapEx (gesamt, fossil, low-carbon), Investments, "
    "OpEx (operativ, energiebezogen). "
    "4. 'cashflow': Operating Cashflow, Free Cashflow, Cashflow from Operations. "
    "5. 'capital_structure': Total Assets, Equity, Debt, Liabilities, "
    "Debt-to-Equity, Leverage, Net Debt. "
    "6. 'energy_consumption': Gesamtenergieverbrauch, Energieintensität. "
    "7. 'emissions_scope1': Scope-1-Emissionen (tCO2e). "
    "8. 'emissions_scope2': Scope-2-Emissionen (tCO2e). "
    "9. 'emissions_scope3': Scope-3-Emissionen (tCO2e). "
    "10. 'emission_intensity': Emissionsintensität (z. B. tCO2e pro Umsatz oder MWh). "

    "Extrahiere ausschließlich KPIs, die im Text explizit und vollständig benannt werden. "
    "Ignoriere qualitative Aussagen, nicht-finanzielle Beschreibungen, Prozentwerte ohne "
    "Referenzgröße, isolierte Zahlen ohne KPI-Bezug, implizite oder geschätzte Werte sowie "
    "Tabellenfragmente ohne ausreichenden Kontext. "

    "Wenn mehrere semantisch identische KPIs vorkommen, gib nur den präzisesten Wert aus. "

    "Erstelle eine JSON-Liste, in der jedes Objekt ausschließlich folgende Felder enthält: "
    "'kpi' (offizielle KPI-Bezeichnung), 'wert' (numerischer Wert exakt wie im Text), "
    "'einheit' (Maßeinheit oder leer), 'kontext' (Originaltextausschnitt) und "
    "'kategorie' (eine der oben definierten Kategorien, keine weiteren Kategorien). "

    "Gib ausschließlich die JSON-Liste aus, ohne zusätzliche Erklärungen oder Kommentare."
)


GREENWASHING_ANALYSIS_PROMPT = (
    "Du bist ein Auditor für Nachhaltigkeitsberichterstattung, der ausschließlich strukturierte JSON-Ausgaben liefert.\n"
    "Du erhältst als Eingabe EIN JSON-Objekt mit den Schlüsseln 'claims' und 'kpis'. "
    "Dieses Objekt repräsentiert GENAU EINEN Batch eines Unternehmens.\n\n"

    "Eingabestruktur:\n"
    "- 'claims': Liste von Objekten { 'text': <Claim-Satz>, 'p_yes': <0–1 optional> }.\n"
    "  'text' enthält einen extrahierten Nachhaltigkeits-Claim.\n"
    "- 'kpis': Liste von Objekten { "
    "'kpi': <Name>, 'value': <Wert als String>, 'unit': <Einheit>, "
    "'context': <Kontext>, 'kategorie': <KPI-Kategorie>, 'reportingyear': <Jahr oder null> }.\n\n"

    "Aufgabe:\n"
    "Für JEDEN Claim in 'claims' sollst du GENAU EIN Ausgabeelement erzeugen, bestehend aus:\n"
    "1) 'claim': Der Claim-Text.\n"
    "2) 'kpis': Eine Liste der relevanten KPIs aus der Eingabe, die du zur Bewertung dieses Claims heranziehst. "
    "   - Die Liste kann leer sein, eine KPI oder mehrere KPIs enthalten.\n"
    "   - Wähle nur KPIs, die inhaltlich zum Claim passen (z.B. gleiche Emissionsart, gleiche Energieart, "
    "     verwandter Geschäftsbereich oder eindeutig verknüpfbare finanzielle Kennzahlen).\n"
    "   - Wenn der Claim eine Entwicklung über die Zeit behauptet (z.B. 'wir reduzieren', 'wir steigern kontinuierlich', "
    "     'bis 2030'), berücksichtige explizit KPI-Werte aus verschiedenen Jahren ('reportingyear'), "
    "     um einen Trend abzuleiten.\n"
    "   - Jede KPI in der Ausgabeliste soll als kurzer String angegeben werden, z.B.: "
    "\"<Name>: <Wert> <Einheit>, Jahr <reportingyear> (<Kontext>)\".\n"
    "3) 'relation': Die aggregierte Beziehung zwischen Claim und den von dir ausgewählten KPIs:\n"
    "   - 'stutzt'       → Die Gesamtheit der ausgewählten KPIs belegt die Aussage plausibel "
    "(z.B. sinkende Emissionen über mehrere Jahre bei einem Reduktions-Claim).\n"
    "   - 'widerspricht' → Die KPIs widersprechen der Aussage klar "
    "(z.B. behauptete Reduktion, aber tatsächlich steigende oder inkonsistente Werte).\n"
    "   - 'kein_beleg'   → Entweder gibt es keine passende KPI oder die vorhandenen KPIs erlauben "
    "keine sinnvolle Bewertung der Aussage (z.B. falscher Bereich, zu wenig oder widersprüchliche Informationen).\n"
    "4) 'rationale': Eine präzise, EINZIGE Begründung (ein deutscher Satz ohne Zeilenumbrüche), "
    "warum du diese Relation gewählt hast. "
    "Beziehe dich dabei auf die ausgewählten KPIs und ggf. auf deren zeitliche Entwicklung.\n\n"

    "WICHTIG:\n"
    "- Du musst ALLE Claims aus 'claims' einzeln bewerten.\n"
    "- Die Ausgabeliste muss GENAU so viele Elemente enthalten wie die Eingabeliste 'claims'.\n"
    "- Du darfst PRO Claim beliebig viele passende KPIs auswählen (inkl. verschiedener Berichtsjahre), "
    "aber du sollst unnötige oder schwach relevante KPIs weglassen.\n"
    "- Wenn KEINE KPI zur Bewertung geeignet ist, setze 'kpis' auf eine leere Liste und 'relation' auf 'kein_beleg'.\n\n"

    "Ausgabeformat (NUR gültiges JSON, KEIN Markdown, KEINE Kommentare):\n"
    "[\n"
    "  {\n"
    "    \"claim\": \"<Claim-Text>\",\n"
    "    \"kpis\": [\n"
    "      \"<Name>: <Wert> <Einheit>, Jahr <reportingyear> (<Kontext>)\",\n"
    "      \"... optional weitere KPIs ...\"\n"
    "    ],\n"
    "    \"relation\": \"stutzt|widerspricht|kein_beleg\",\n"
    "    \"rationale\": \"<ein deutscher Satz>\"\n"
    "  }\n"
    "]\n\n"

    "Strikte Regeln:\n"
    "- Gib ausschließlich diese JSON-LISTE aus.\n"
    "- Keine erläuternden Texte.\n"
    "- Keine Backticks.\n"
    "- Keine zusätzlichen Felder.\n"
)
