"""Centralised prompt templates for the OpenRouter LLM calls."""

KPI_EXTRACTION_PROMPT = (
    "Extrahiere die wichtigsten finanziellen Kennzahlen aus dem folgenden Text. "
    "Gib das Ergebnis als JSON-Liste mit den Feldern 'kpi', 'wert', 'einheit' "
    "und 'kontext' zurück. Verwende numerische Werte, sofern vorhanden, und "
    "lasse das Feld 'einheit' leer, wenn keine Einheit genannt wird."
)

GREENWASHING_ANALYSIS_PROMPT = (
    "Du bist ein Auditor für Nachhaltigkeitsberichte. Du erhältst eine JSON-Eingabe "
    "mit zwei Schlüsseln: 'claims' und 'kpis'.\n\n"
    "Eingabestruktur:\n"
    "- claims: Liste von Objekten der Form\n"
    "  {\"text\": <Claim-Satz>, \"p_yes\": <Wahrscheinlichkeit (0–1), dass der Satz ein ESG-Claim ist>}.\n"
    "  'p_yes' dient als Vertrauensindikator und darf in die Bewertung einfließen.\n"
    "- kpis: Liste von Finanzkennzahlen-Objekten der Form\n"
    "  {\"kpi\": <Name>, \"value\": <Wert als String>, \"unit\": <Einheit>, \"context\": <Kontext>}\n"
    "  z.B. {\"kpi\": \"Potential annual increase in insurance premiums\", \"value\": \"2.0\", "
    "\"unit\": \"million EUR\", \"context\": \"due to climate change by 2040\"} oder "
    "{\"kpi\": \"Annual cost rise due to emissions (RCP1.9 scenario)\", \"value\": \"9.2\", "
    "\"unit\": \"%\", \"context\": \"by 2030\"}.\n\n"
    "Aufgabe:\n"
    "Bewerte, ob die Nachhaltigkeitsaussagen ('claims') durch die berichteten Finanzdaten ('kpis') "
    "inhaltlich und quantitativ plausibel gestützt werden. Begründe Verdacht auf Greenwashing bei "
    "Widersprüchen, fehlenden Belegen, unplausiblen Größenordnungen oder Trends.\n\n"
    "Ausgabeformat (NUR gültiges JSON, ohne Zusatztext):\n"
    "{\n"
    "  \"verdaechtiger_score\": <Zahl 0–1>,\n"
    "  \"einschaetzung\": \"Kurzer prägnanter deutscher Satz\",\n"
    "  \"rationales\": [\"Begründung 1\", \"Begründung 2\", ...],\n"
    "  \"evidence\": {\n"
    "    \"claim_to_kpi_links\": [\n"
    "      {\"claim_index\": <int>, \"kpi_index\": <int>, \"relation\": \"stutzt|widerspricht|irrelevant\", "
    "\"note\": \"kurze Begründung\"}\n"
    "    ]\n"
    "  }\n"
    "}\n\n"
    "Spezifikation der Begründungen ('rationales'):\n"
    "- Jede Begründung muss aus drei klar erkennbaren Bestandteilen bestehen:\n"
    "  1) Kurzbeschreibung des Claims\n"
    "  2) Benannte KPI oder Hinweis 'kein Beleg vorhanden'\n"
    "  3) Schlussfolgerung zur Plausibilität oder zum Verdacht\n\n"
    "  Beispiele:\n"
    "  \"Claim: Emissionsreduktion | KPI: keine relevante Emissionskennzahl vorhanden | Schlussfolgerung: fehlende Belegbarkeit.\"\n"
    "  \"Claim: Investitionshöhe | KPI: 'Sustainable CapEx' = 2.1 Mio. EUR | Schlussfolgerung: Größenordnung plausibel.\"\n"
    "  \"Claim: Trendwende behauptet | KPI zeigt gegenteilige Entwicklung | Schlussfolgerung: möglicher Greenwashing-Verdacht.\"\n\n"
    "- Formuliere präzise, fakten- und datenbasiert, ohne allgemeine oder vage Aussagen.\n"
    "- 'claim_to_kpi_links' dokumentiert den Audit-Trail: Welche KPI begründet welche Einschätzung zu welchem Claim.\n"
    "- Wenn keine ausreichenden Belege vorliegen, benenne dies explizit und setze die Relation auf 'irrelevant' oder 'unbelegt'.\n"
    "- Keine verborgenen Denkschritte, keine Chain-of-Thought. Antworte kompakt, faktenbasiert und prüfbar.\n"
    "- Gib ausschließlich syntaktisch gültiges JSON zurück (keine Erklärtexte, kein Markdown).\n"
)
